#!/data/data/com.termux/files/usr/bin/bash
set -eu

# C5V3 R10 Shadow Runner Materialize R1
# Build/audit only. Does NOT execute runner, VM, core, network, cataloger, or state loop.
# Exact known files only. No directory walk, no find, no recursive grep.

ROOT="${1:-$HOME/SIGMA/sigma_genesis1}"
LIVE_INSTALL="$ROOT/.sigma_c5"
SYNC_ROOT="$ROOT/.sigma_c5v3_sync"
STAGE_ROOT="$SYNC_ROOT/C5V3_R10_SUCCESSOR_STAGE_R1"
STAGE_INSTALL="$STAGE_ROOT/install"
STAGE_STATE="$STAGE_ROOT/state"

LIVE_RUNNER="$LIVE_INSTALL/control/RUN_SIGMA_C5_AUTONOMOUS_SELF_LEARNING_OPPO_V3_REFLECTIVE.sh"
SIGMAC="$ROOT/native/sigmac"
VM="$ROOT/native/sigma-vm.v09_candidate"
LIVE_SOURCE="$LIVE_INSTALL/src/SIGMA_C5_AUTONOMOUS_SELF_LEARNING_CORE_V1.sigma"

STAGED_SOURCE="$STAGE_INSTALL/src/SIGMA_C5_AUTONOMOUS_SELF_LEARNING_CORE_V1.sigma"
STAGED_BYTECODE="$STAGE_INSTALL/bin/SIGMA_C5_AUTONOMOUS_SELF_LEARNING_CORE_V1.sigmab"

LIVE_BRIDGE="$LIVE_INSTALL/tools/SIGMA_C5_MECHANICAL_BRIDGE_V2.py"
LIVE_REVIEW_SOURCE="$LIVE_INSTALL/src/SIGMA_C5_NATIVE_REFLECTIVE_REVIEW_V3.sigma"
LIVE_REVIEW_BRIDGE="$LIVE_INSTALL/tools/SIGMA_C5_MECHANICAL_REVIEW_BRIDGE_V3.py"
LIVE_REVIEW_BYTECODE="$LIVE_INSTALL/bin/SIGMA_C5_NATIVE_REFLECTIVE_REVIEW_V3.sigmab"

STAGED_BRIDGE="$STAGE_INSTALL/tools/SIGMA_C5_MECHANICAL_BRIDGE_V2.py"
STAGED_REVIEW_SOURCE="$STAGE_INSTALL/src/SIGMA_C5_NATIVE_REFLECTIVE_REVIEW_V3.sigma"
STAGED_REVIEW_BRIDGE="$STAGE_INSTALL/tools/SIGMA_C5_MECHANICAL_REVIEW_BRIDGE_V3.py"
STAGED_REVIEW_BYTECODE="$STAGE_INSTALL/bin/SIGMA_C5_NATIVE_REFLECTIVE_REVIEW_V3.sigmab"

SHADOW_CONTROL="$STAGE_ROOT/control"
SHADOW_RUNNER="$SHADOW_CONTROL/RUN_SIGMA_C5V3_R10_SHADOW_R1.sh"
MANIFEST="$STAGE_ROOT/evidence/SHADOW_RUNNER_MATERIALIZE_R1.txt"

EXPECTED_LIVE_RUNNER_SHA256="092c6ad96823ba578ba5a8e22fe5f9d45a80c9ae4cc380b7296a5da3ec6a8847"
EXPECTED_LIVE_SOURCE_SHA256="23d51badf90a409d08e740d8badb3c0eb8f85e97dc83b8016225459b02affbcc"
EXPECTED_SIGMAC_SHA256="65f69217ad44f33c1aa1d4c31678d38940cd3d0b96f41892e8280dac57ad6a71"
EXPECTED_VM_SHA256="029ae4b6acbee5558f7663a732f8d39a970166e8488d2c4fe62414eb39391c99"
EXPECTED_R10_SOURCE_SHA256="7d9e91f9a5a7fa265ca4304084fc48aca105b74ae7ca08662398b535c8d3cd34"
EXPECTED_R10_BYTECODE_SHA256="c837fcc03f79f64487d9146fc268783c13bf0769352a2068492c1d4374b109c5"
EXPECTED_LIVE_REVIEW_SOURCE_SHA256="95fac3da14a79b969a362d0dadd7823b66612c91d6dca4b0f4b5708f1eb010b7"
EXPECTED_LIVE_REVIEW_BYTECODE_SHA256="424742773403cfb3c0ffcce0615b2cc8ff0998c5c2e828b313820b8fe817e4d3"

hash1() {
  sha256sum "$1" 2>/dev/null | awk '{print $1}'
}

hold() {
  printf 'SHADOW_RUNNER_MATERIALIZE=HOLD_%s\n' "$1"
  printf 'SHADOW_RUNNER_EXECUTION=NO\n'
  printf 'PRODUCTION_BINDING=NO\n'
  printf 'PRODUCTION_MUTATION=NO\n'
  exit 0
}

require_hash() {
  label="$1"
  path="$2"
  expected="$3"
  [ -f "$path" ] || hold "${label}_MISSING"
  actual=$(hash1 "$path")
  printf '%s_PATH=%s\n' "$label" "$path"
  printf '%s_SHA256=%s\n' "$label" "$actual"
  [ "$actual" = "$expected" ] || hold "${label}_IDENTITY_MISMATCH"
  printf '%s_IDENTITY=PASS\n' "$label"
}

extract_assign() {
  var="$1"
  count=$(grep -Ec "^${var}=" "$LIVE_RUNNER" 2>/dev/null || true)
  [ "$count" -eq 1 ] || hold "RUNNER_${var}_ASSIGNMENT_COUNT_${count}"
  raw=$(grep -E "^${var}=" "$LIVE_RUNNER" | head -n 1)
  raw=${raw#*=}
  case "$raw" in
    \"*\") raw=${raw#\"}; raw=${raw%\"} ;;
    \'*\') raw=${raw#\'}; raw=${raw%\'} ;;
  esac
  printf '%s' "$raw"
}

stage_copy_exact() {
  label="$1"
  src="$2"
  dst="$3"
  expected="$4"
  if [ -f "$dst" ]; then
    actual=$(hash1 "$dst")
    [ "$actual" = "$expected" ] || hold "EXISTING_${label}_MISMATCH"
    printf '%s_STAGE_EXISTING=PASS\n' "$label"
    return 0
  fi
  cp "$src" "$dst.partial"
  actual=$(hash1 "$dst.partial")
  [ "$actual" = "$expected" ] || hold "${label}_COPY_MISMATCH"
  mv "$dst.partial" "$dst"
  printf '%s_STAGE_COPY=PASS\n' "$label"
}

printf '%s\n' '=== C5V3 R10 SHADOW RUNNER MATERIALIZE R1 ==='
printf 'ROOT=%s\n' "$ROOT"
printf 'MODE=MATERIALIZE_AND_AUDIT_ONLY\n'
printf 'EXACT_PATHS_ONLY=YES\n'
printf 'DIRECTORY_WALK=NO\n'
printf 'FIND=NO\n'
printf 'GREP_RECURSIVE=NO\n'
printf 'RUNNER_EXECUTION=NO\n'
printf 'VM_EXECUTION=NO\n'
printf 'CORE_EXECUTION=NO\n'
printf 'NETWORK=NO\n'
printf 'CATALOGER_EXECUTION=NO\n'
printf 'LIVE_STATE_WRITE=NO\n'
printf 'LIVE_CORE_WRITE=NO\n'
printf 'PRODUCTION_BINDING=NO\n'
printf 'PRODUCTION_MUTATION=NO\n'

printf '%s\n' '=== 1. EXACT IDENTITY LOCKS ==='
require_hash LIVE_RUNNER "$LIVE_RUNNER" "$EXPECTED_LIVE_RUNNER_SHA256"
require_hash LIVE_MAIN_SOURCE "$LIVE_SOURCE" "$EXPECTED_LIVE_SOURCE_SHA256"
require_hash LOCKED_SIGMAC "$SIGMAC" "$EXPECTED_SIGMAC_SHA256"
require_hash LOCKED_VM "$VM" "$EXPECTED_VM_SHA256"
require_hash STAGED_R10_SOURCE "$STAGED_SOURCE" "$EXPECTED_R10_SOURCE_SHA256"
require_hash STAGED_R10_BYTECODE "$STAGED_BYTECODE" "$EXPECTED_R10_BYTECODE_SHA256"
require_hash LIVE_REVIEW_SOURCE "$LIVE_REVIEW_SOURCE" "$EXPECTED_LIVE_REVIEW_SOURCE_SHA256"
require_hash LIVE_REVIEW_BYTECODE "$LIVE_REVIEW_BYTECODE" "$EXPECTED_LIVE_REVIEW_BYTECODE_SHA256"

printf '%s\n' '=== 2. RUNNER-LOCKED DEPENDENCY IDENTITIES ==='
RUNNER_EXPECTED_NATIVE_SOURCE=$(extract_assign EXPECTED_NATIVE_SOURCE)
RUNNER_EXPECTED_BRIDGE=$(extract_assign EXPECTED_MECHANICAL_BRIDGE)
RUNNER_EXPECTED_REVIEW_SOURCE=$(extract_assign EXPECTED_REVIEW_SOURCE)
RUNNER_EXPECTED_REVIEW_BRIDGE=$(extract_assign EXPECTED_REVIEW_BRIDGE)

printf 'RUNNER_EXPECTED_NATIVE_SOURCE=%s\n' "$RUNNER_EXPECTED_NATIVE_SOURCE"
printf 'RUNNER_EXPECTED_MECHANICAL_BRIDGE=%s\n' "$RUNNER_EXPECTED_BRIDGE"
printf 'RUNNER_EXPECTED_REVIEW_SOURCE=%s\n' "$RUNNER_EXPECTED_REVIEW_SOURCE"
printf 'RUNNER_EXPECTED_REVIEW_BRIDGE=%s\n' "$RUNNER_EXPECTED_REVIEW_BRIDGE"

[ "$RUNNER_EXPECTED_NATIVE_SOURCE" = "$EXPECTED_LIVE_SOURCE_SHA256" ] || hold RUNNER_PARENT_SOURCE_EXPECTATION_CHANGED
[ "$RUNNER_EXPECTED_REVIEW_SOURCE" = "$EXPECTED_LIVE_REVIEW_SOURCE_SHA256" ] || hold RUNNER_REVIEW_SOURCE_EXPECTATION_CHANGED

require_hash LIVE_MECHANICAL_BRIDGE "$LIVE_BRIDGE" "$RUNNER_EXPECTED_BRIDGE"
require_hash LIVE_REVIEW_BRIDGE "$LIVE_REVIEW_BRIDGE" "$RUNNER_EXPECTED_REVIEW_BRIDGE"

printf '%s\n' '=== 3. MATERIALIZE EXACT SHADOW DEPENDENCIES ==='
mkdir -p "$STAGE_INSTALL/src" "$STAGE_INSTALL/bin" "$STAGE_INSTALL/tools" "$SHADOW_CONTROL" "$STAGE_STATE" "$STAGE_ROOT/evidence"
stage_copy_exact MECHANICAL_BRIDGE "$LIVE_BRIDGE" "$STAGED_BRIDGE" "$RUNNER_EXPECTED_BRIDGE"
stage_copy_exact REVIEW_SOURCE "$LIVE_REVIEW_SOURCE" "$STAGED_REVIEW_SOURCE" "$EXPECTED_LIVE_REVIEW_SOURCE_SHA256"
stage_copy_exact REVIEW_BRIDGE "$LIVE_REVIEW_BRIDGE" "$STAGED_REVIEW_BRIDGE" "$RUNNER_EXPECTED_REVIEW_BRIDGE"
stage_copy_exact REVIEW_BYTECODE "$LIVE_REVIEW_BYTECODE" "$STAGED_REVIEW_BYTECODE" "$EXPECTED_LIVE_REVIEW_BYTECODE_SHA256"

# Keep exact frozen bytecodes newer than their sources so a later admitted shadow run
# does not recompile them merely because of copy timestamps. This changes metadata only.
if [ "$STAGED_SOURCE" -nt "$STAGED_BYTECODE" ]; then
  touch "$STAGED_BYTECODE"
  printf 'STAGED_MAIN_BYTECODE_MTIME_REFRESHED=YES\n'
else
  printf 'STAGED_MAIN_BYTECODE_MTIME_REFRESHED=NO\n'
fi
if [ "$STAGED_REVIEW_SOURCE" -nt "$STAGED_REVIEW_BYTECODE" ]; then
  touch "$STAGED_REVIEW_BYTECODE"
  printf 'STAGED_REVIEW_BYTECODE_MTIME_REFRESHED=YES\n'
else
  printf 'STAGED_REVIEW_BYTECODE_MTIME_REFRESHED=NO\n'
fi
require_hash STAGED_R10_BYTECODE_AFTER_MTIME "$STAGED_BYTECODE" "$EXPECTED_R10_BYTECODE_SHA256"
require_hash STAGED_REVIEW_BYTECODE_AFTER_MTIME "$STAGED_REVIEW_BYTECODE" "$EXPECTED_LIVE_REVIEW_BYTECODE_SHA256"

printf '%s\n' '=== 4. MECHANICALLY DERIVE SHADOW RUNNER ==='
INSTALL_ASSIGN_COUNT=$(grep -Fxc 'INSTALL="$ROOT/.sigma_c5"' "$LIVE_RUNNER" 2>/dev/null || true)
C5_ASSIGN_COUNT=$(grep -Fxc 'C5="${C5_STATE_ROOT:-$INSTALL}"' "$LIVE_RUNNER" 2>/dev/null || true)
EXPECTED_NATIVE_ASSIGN_COUNT=$(grep -Ec '^EXPECTED_NATIVE_SOURCE=' "$LIVE_RUNNER" 2>/dev/null || true)
printf 'LIVE_INSTALL_ASSIGN_COUNT=%s\n' "$INSTALL_ASSIGN_COUNT"
printf 'LIVE_C5_ASSIGN_COUNT=%s\n' "$C5_ASSIGN_COUNT"
printf 'LIVE_EXPECTED_NATIVE_SOURCE_ASSIGN_COUNT=%s\n' "$EXPECTED_NATIVE_ASSIGN_COUNT"
[ "$INSTALL_ASSIGN_COUNT" -eq 1 ] || hold INSTALL_ASSIGNMENT_NOT_UNIQUE
[ "$C5_ASSIGN_COUNT" -eq 1 ] || hold C5_ASSIGNMENT_NOT_UNIQUE
[ "$EXPECTED_NATIVE_ASSIGN_COUNT" -eq 1 ] || hold EXPECTED_NATIVE_SOURCE_ASSIGNMENT_NOT_UNIQUE

sed \
  -e 's|^INSTALL="\$ROOT/\.sigma_c5"$|INSTALL="$ROOT/.sigma_c5v3_sync/C5V3_R10_SUCCESSOR_STAGE_R1/install"|' \
  -e 's|^C5="\${C5_STATE_ROOT:-\$INSTALL}"$|C5="${C5_STATE_ROOT:-$ROOT/.sigma_c5v3_sync/C5V3_R10_SUCCESSOR_STAGE_R1/state}"|' \
  -e 's|^EXPECTED_NATIVE_SOURCE=.*$|EXPECTED_NATIVE_SOURCE=7d9e91f9a5a7fa265ca4304084fc48aca105b74ae7ca08662398b535c8d3cd34|' \
  "$LIVE_RUNNER" > "$SHADOW_RUNNER.partial"

bash -n "$SHADOW_RUNNER.partial" || hold SHADOW_RUNNER_SHELL_SYNTAX

SHADOW_INSTALL_ASSIGN_COUNT=$(grep -Fxc 'INSTALL="$ROOT/.sigma_c5v3_sync/C5V3_R10_SUCCESSOR_STAGE_R1/install"' "$SHADOW_RUNNER.partial" 2>/dev/null || true)
SHADOW_C5_ASSIGN_COUNT=$(grep -Fxc 'C5="${C5_STATE_ROOT:-$ROOT/.sigma_c5v3_sync/C5V3_R10_SUCCESSOR_STAGE_R1/state}"' "$SHADOW_RUNNER.partial" 2>/dev/null || true)
SHADOW_EXPECTED_NATIVE_COUNT=$(grep -Fxc 'EXPECTED_NATIVE_SOURCE=7d9e91f9a5a7fa265ca4304084fc48aca105b74ae7ca08662398b535c8d3cd34' "$SHADOW_RUNNER.partial" 2>/dev/null || true)
ORIGINAL_INSTALL_ASSIGN_REMAINING=$(grep -Fxc 'INSTALL="$ROOT/.sigma_c5"' "$SHADOW_RUNNER.partial" 2>/dev/null || true)
ORIGINAL_C5_ASSIGN_REMAINING=$(grep -Fxc 'C5="${C5_STATE_ROOT:-$INSTALL}"' "$SHADOW_RUNNER.partial" 2>/dev/null || true)

printf 'SHADOW_INSTALL_ASSIGN_COUNT=%s\n' "$SHADOW_INSTALL_ASSIGN_COUNT"
printf 'SHADOW_C5_ASSIGN_COUNT=%s\n' "$SHADOW_C5_ASSIGN_COUNT"
printf 'SHADOW_EXPECTED_NATIVE_SOURCE_ASSIGN_COUNT=%s\n' "$SHADOW_EXPECTED_NATIVE_COUNT"
printf 'ORIGINAL_INSTALL_ASSIGN_REMAINING=%s\n' "$ORIGINAL_INSTALL_ASSIGN_REMAINING"
printf 'ORIGINAL_C5_ASSIGN_REMAINING=%s\n' "$ORIGINAL_C5_ASSIGN_REMAINING"

[ "$SHADOW_INSTALL_ASSIGN_COUNT" -eq 1 ] || hold SHADOW_INSTALL_PATCH_FAILED
[ "$SHADOW_C5_ASSIGN_COUNT" -eq 1 ] || hold SHADOW_C5_PATCH_FAILED
[ "$SHADOW_EXPECTED_NATIVE_COUNT" -eq 1 ] || hold SHADOW_EXPECTED_NATIVE_PATCH_FAILED
[ "$ORIGINAL_INSTALL_ASSIGN_REMAINING" -eq 0 ] || hold LIVE_INSTALL_BINDING_REMAINS
[ "$ORIGINAL_C5_ASSIGN_REMAINING" -eq 0 ] || hold LIVE_C5_DEFAULT_BINDING_REMAINS

if [ -f "$SHADOW_RUNNER" ]; then
  existing_sha=$(hash1 "$SHADOW_RUNNER")
  new_sha=$(hash1 "$SHADOW_RUNNER.partial")
  [ "$existing_sha" = "$new_sha" ] || hold EXISTING_SHADOW_RUNNER_DIFFERS
  rm -f "$SHADOW_RUNNER.partial"
  printf 'SHADOW_RUNNER_ALREADY_EXISTS=YES\n'
else
  mv "$SHADOW_RUNNER.partial" "$SHADOW_RUNNER"
  chmod 0500 "$SHADOW_RUNNER"
  printf 'SHADOW_RUNNER_ALREADY_EXISTS=NO\n'
fi

SHADOW_RUNNER_SHA=$(hash1 "$SHADOW_RUNNER")
printf 'SHADOW_RUNNER_PATH=%s\n' "$SHADOW_RUNNER"
printf 'SHADOW_RUNNER_SHA256=%s\n' "$SHADOW_RUNNER_SHA"
printf 'SHADOW_RUNNER_SHELL_SYNTAX=PASS\n'

printf '%s\n' '=== 5. SHARED-ROOT / EXECUTION SAFETY AUDIT ==='
ROOT_NATIVE_REF_COUNT=$(grep -Ec '\$ROOT/\.sigma_native' "$SHADOW_RUNNER" 2>/dev/null || true)
printf 'ROOT_SIGMA_NATIVE_REFERENCE_COUNT=%s\n' "$ROOT_NATIVE_REF_COUNT"
if [ "$ROOT_NATIVE_REF_COUNT" -gt 0 ]; then
  grep -nE '\$ROOT/\.sigma_native' "$SHADOW_RUNNER" 2>/dev/null | head -n 20 || true
fi
printf 'CATALOGER_CONTRACT_RECONCILED=NO\n'
printf 'NETWORK_FETCH_CONTRACT_RECONCILED=NO\n'
printf 'SHADOW_RUNNER_EXECUTION=NO_PENDING_CATALOG_AND_SHARED_ROOT_RECONCILIATION\n'

cat > "$MANIFEST" <<EOF
ONE_SIGMA=YES
SYSTEM=C5V3
MATERIALIZATION_ID=C5V3_R10_SHADOW_RUNNER_MATERIALIZE_R1
LIVE_RUNNER_SHA256=$EXPECTED_LIVE_RUNNER_SHA256
R10_SOURCE_SHA256=$EXPECTED_R10_SOURCE_SHA256
R10_BYTECODE_SHA256=$EXPECTED_R10_BYTECODE_SHA256
SHADOW_RUNNER_SHA256=$SHADOW_RUNNER_SHA
SHADOW_INSTALL=$STAGE_INSTALL
SHADOW_STATE=$STAGE_STATE
RUNNER_EXPECTED_MECHANICAL_BRIDGE=$RUNNER_EXPECTED_BRIDGE
RUNNER_EXPECTED_REVIEW_SOURCE=$RUNNER_EXPECTED_REVIEW_SOURCE
RUNNER_EXPECTED_REVIEW_BRIDGE=$RUNNER_EXPECTED_REVIEW_BRIDGE
ROOT_SIGMA_NATIVE_REFERENCE_COUNT=$ROOT_NATIVE_REF_COUNT
CATALOGER_CONTRACT_RECONCILED=NO
NETWORK_FETCH_CONTRACT_RECONCILED=NO
SHADOW_RUNNER_EXECUTION=NO
PRODUCTION_BINDING=NO
PRODUCTION_MUTATION=NO
EOF

printf '%s\n' '=== 6. LIVE NON-MUTATION RECHECK ==='
require_hash LIVE_RUNNER_AFTER "$LIVE_RUNNER" "$EXPECTED_LIVE_RUNNER_SHA256"
require_hash LIVE_MAIN_SOURCE_AFTER "$LIVE_SOURCE" "$EXPECTED_LIVE_SOURCE_SHA256"

printf '%s\n' '=== 7. RESULT ==='
printf 'SHADOW_RUNNER_MATERIALIZE=PASS\n'
printf 'R10_SHADOW_INSTALL_BINDING_MATERIALIZED=YES\n'
printf 'R10_SHADOW_STATE_BINDING_MATERIALIZED=YES\n'
printf 'EXACT_BRIDGE_REVIEW_DEPENDENCIES_STAGED=YES\n'
printf 'R10_EXPECTED_MAIN_SOURCE_IDENTITY_PATCHED=YES\n'
printf 'SHADOW_RUNNER_EXECUTION=NO\n'
printf 'LIVE_CORE_UNCHANGED=YES\n'
printf 'LIVE_RUNNER_UNCHANGED=YES\n'
printf 'PRODUCTION_BINDING=NO\n'
printf 'PRODUCTION_MUTATION=NO\n'
printf '%s\n' '=== END ==='
