#!/data/data/com.termux/files/usr/bin/bash
set -eu

# C5V3 Core Rewrite R2 — Compile/Freeze R1
# Exact-path isolated compile only. No VM/core execution. No production write.

ROOT="${1:-$HOME/SIGMA/sigma_genesis1}"
REWRITE_ROOT="$ROOT/.sigma_c5v3_sync/C5V3_CORE_REWRITE_R2"
SRC="$REWRITE_ROOT/src/SIGMA_C5_AUTONOMOUS_SELF_LEARNING_CORE_V1.sigma"
BIN_DIR="$REWRITE_ROOT/bin"
BIN="$BIN_DIR/SIGMA_C5_AUTONOMOUS_SELF_LEARNING_CORE_V1.sigmab"
SIGMAC="$ROOT/native/sigmac"
LIVE_SRC="$ROOT/.sigma_c5/src/SIGMA_C5_AUTONOMOUS_SELF_LEARNING_CORE_V1.sigma"
LIVE_RUNNER="$ROOT/.sigma_c5/control/RUN_SIGMA_C5_AUTONOMOUS_SELF_LEARNING_OPPO_V3_REFLECTIVE.sh"
MANIFEST="$REWRITE_ROOT/evidence/COMPILE_FREEZE_R1.txt"

EXPECTED_SRC_SHA256="d7d1153fd6979dff7d119bb5e8187f045b9f8af62e51065cccf95265478fc3a0"
EXPECTED_SIGMAC_SHA256="65f69217ad44f33c1aa1d4c31678d38940cd3d0b96f41892e8280dac57ad6a71"
EXPECTED_LIVE_SRC_SHA256="23d51badf90a409d08e740d8badb3c0eb8f85e97dc83b8016225459b02affbcc"
EXPECTED_LIVE_RUNNER_SHA256="092c6ad96823ba578ba5a8e22fe5f9d45a80c9ae4cc380b7296a5da3ec6a8847"
EXPECTED_HEADER='#SIGMAUNIVERSE_LANGUAGE[DOMAIN=SIGMA.C5.AUTONOMOUS.SELF.LEARNING.CORE][VERSION=C5FULLR1]'

hash1() {
  sha256sum "$1" 2>/dev/null | awk '{print $1}'
}

hold() {
  printf 'CORE_REWRITE_R2_COMPILE_FREEZE=HOLD_%s\n' "$1"
  printf 'VM_EXECUTION=NO\n'
  printf 'PRODUCTION_BINDING=NO\n'
  printf 'PRODUCTION_MUTATION=NO\n'
  exit 0
}

require_hash() {
  label="$1"
  path="$2"
  expected="$3"
  [ -f "$path" ] || hold "${label}_MISSING"
  actual=$(hash1 "$path")
  printf '%s_PATH=%s\n' "$label" "$path"
  printf '%s_SHA256=%s\n' "$label" "$actual"
  [ "$actual" = "$expected" ] || hold "${label}_IDENTITY_MISMATCH"
  printf '%s_IDENTITY=PASS\n' "$label"
}

printf '%s\n' '=== C5V3 CORE REWRITE R2 COMPILE FREEZE R1 ==='
printf 'ROOT=%s\n' "$ROOT"
printf 'MODE=ISOLATED_COMPILE_AND_BYTECODE_FREEZE\n'
printf 'EXACT_PATHS_ONLY=YES\n'
printf 'DIRECTORY_SCAN=NO\n'
printf 'VM_EXECUTION=NO\n'
printf 'CORE_EXECUTION=NO\n'
printf 'LIVE_CORE_WRITE=NO\n'
printf 'LIVE_RUNNER_WRITE=NO\n'
printf 'PRODUCTION_BINDING=NO\n'
printf 'PRODUCTION_MUTATION=NO\n'

printf '%s\n' '=== 1. IDENTITY LOCKS ==='
require_hash SUCCESSOR_SOURCE "$SRC" "$EXPECTED_SRC_SHA256"
require_hash LOCKED_SIGMAC "$SIGMAC" "$EXPECTED_SIGMAC_SHA256"
require_hash LIVE_MAIN_SOURCE "$LIVE_SRC" "$EXPECTED_LIVE_SRC_SHA256"
require_hash LIVE_RUNNER "$LIVE_RUNNER" "$EXPECTED_LIVE_RUNNER_SHA256"

HEADER=$(sed -n '1p' "$SRC")
printf 'SUCCESSOR_HEADER=%s\n' "$HEADER"
[ "$HEADER" = "$EXPECTED_HEADER" ] || hold SUCCESSOR_HEADER_MISMATCH
printf 'CORE_IDENTITY_CONTINUITY=PASS\n'

printf '%s\n' '=== 2. COMPILE ==='
mkdir -p "$BIN_DIR" "$REWRITE_ROOT/evidence"
PARTIAL="$BIN.partial.$$"
rm -f -- "$PARTIAL"

set +e
"$SIGMAC" "$SRC" "$PARTIAL"
SIGMAC_RC=$?
set -e
printf 'SIGMAC_RC=%s\n' "$SIGMAC_RC"

[ "$SIGMAC_RC" -eq 0 ] || {
  rm -f -- "$PARTIAL"
  printf 'CORE_REWRITE_R2_COMPILE=FAIL\n'
  printf 'BYTECODE_FREEZE=NO\n'
  printf 'VM_EXECUTION=NO\n'
  printf 'PRODUCTION_BINDING=NO\n'
  printf 'PRODUCTION_MUTATION=NO\n'
  exit 0
}

[ -s "$PARTIAL" ] || hold COMPILED_BYTECODE_EMPTY
NEW_BIN_SHA=$(hash1 "$PARTIAL")
printf 'COMPILED_BYTECODE_SHA256=%s\n' "$NEW_BIN_SHA"

if [ -f "$BIN" ]; then
  EXISTING_SHA=$(hash1 "$BIN")
  printf 'EXISTING_BYTECODE_SHA256=%s\n' "$EXISTING_SHA"
  if [ "$EXISTING_SHA" != "$NEW_BIN_SHA" ]; then
    rm -f -- "$PARTIAL"
    hold EXISTING_BYTECODE_DIFFERS
  fi
  rm -f -- "$PARTIAL"
  printf 'BYTECODE_ALREADY_EXISTS=YES\n'
else
  mv "$PARTIAL" "$BIN"
  chmod 0400 "$BIN"
  printf 'BYTECODE_ALREADY_EXISTS=NO\n'
fi

FINAL_BIN_SHA=$(hash1 "$BIN")
printf 'BYTECODE_PATH=%s\n' "$BIN"
printf 'BYTECODE_SHA256=%s\n' "$FINAL_BIN_SHA"
[ "$FINAL_BIN_SHA" = "$NEW_BIN_SHA" ] || hold FINAL_BYTECODE_HASH_MISMATCH

printf '%s\n' '=== 3. SOURCE/LIVE NON-MUTATION RECHECK ==='
require_hash SUCCESSOR_SOURCE_AFTER "$SRC" "$EXPECTED_SRC_SHA256"
require_hash LIVE_MAIN_SOURCE_AFTER "$LIVE_SRC" "$EXPECTED_LIVE_SRC_SHA256"
require_hash LIVE_RUNNER_AFTER "$LIVE_RUNNER" "$EXPECTED_LIVE_RUNNER_SHA256"

cat > "$MANIFEST" <<EOF
ONE_SIGMA=YES
SYSTEM=C5V3
CORE_LINEAGE=SIGMA.C5.AUTONOMOUS.SELF.LEARNING.CORE
CORE_VERSION=C5FULLR1
SUCCESSOR_SOURCE_SHA256=$EXPECTED_SRC_SHA256
SUCCESSOR_BYTECODE_SHA256=$FINAL_BIN_SHA
SIGMAC_SHA256=$EXPECTED_SIGMAC_SHA256
CORE_IDENTITY_CONTINUITY=PASS
CORE_REWRITE_R2_COMPILE=PASS
BYTECODE_FREEZE=PASS
VM_EXECUTION=NO
PRODUCTION_BINDING=NO
PRODUCTION_MUTATION=NO
EOF

printf '%s\n' '=== 4. RESULT ==='
printf 'CORE_REWRITE_R2_COMPILE=PASS\n'
printf 'BYTECODE_FREEZE=PASS\n'
printf 'CORE_IDENTITY_CONTINUITY=PASS\n'
printf 'CAPABILITY_NATIVE_ARCHITECTURE_COMPILED_IN_SAME_C5_CORE=YES\n'
printf 'VM_EXECUTION=NO\n'
printf 'LIVE_CORE_UNCHANGED=YES\n'
printf 'LIVE_RUNNER_UNCHANGED=YES\n'
printf 'PRODUCTION_BINDING=NO\n'
printf 'PRODUCTION_MUTATION=NO\n'
printf '%s\n' '=== END ==='
