#!/data/data/com.termux/files/usr/bin/bash
set -u
set -o pipefail
umask 077

P=/data/data/com.termux/files/usr
HOME_SIGMA=/data/data/com.termux/files/home/SIGMA
REPO="$HOME_SIGMA/sigma-freedom-write"
PROD_STATE="$HOME_SIGMA/SIGMA_CONTINUOUS_NATIVE_V2_2"
RAW="$PROD_STATE/raw"
HOLD="$PROD_STATE/hold"
BASE="$HOME_SIGMA/SIGMA_V4B3R1_REAL_49C16_RC9_REPLAY_PREFLIGHT"
LOCK="$BASE/preflight.lock"
RUN_ID="$("$P/bin/date" +%s).$$"
STATE="$BASE/run.$RUN_ID"
SHADOW="$STATE/shadow"
BRAIN="$SHADOW/BRAIN/EXTRA BRAIN_OPPO_24826"
E="$BRAIN/.sigma_exec"
LOG="$STATE/log"

SIGMAC="$HOME_SIGMA/sigma_genesis1/native/sigmac"
VM="$HOME_SIGMA/sigma_genesis1/native/sigma-vm.v09_candidate"
EXPECTED_SIGMAC=65f69217ad44f33c1aa1d4c31678d38940cd3d0b96f41892e8280dac57ad6a71
EXPECTED_VM=029ae4b6acbee5558f7663a732f8d39a970166e8488d2c4fe62414eb39391c99
SRC_REPO="$REPO/SIGMA_PROFESSOR/artifacts/SIGMA_V4_TOKEN_WINDOW_RECEIVED_CONTEXT_LEARNER_V4B3.sigma"
SRC="$E/SIGMA_V4_TOKEN_WINDOW_RECEIVED_CONTEXT_LEARNER_V4B3.sigma"
BC="$E/SIGMA_V4_TOKEN_WINDOW_RECEIVED_CONTEXT_LEARNER_V4B3.sigmab"
EXPECTED_SOURCE=8a5687b4e83d74947dd9b1ca1a2729be104eff3d4b935cc64c6ef800f628af83

CONTEXT=49c16c567fcbd0df0241b249e2b51dbf8e20d23ec1dc78ff8d92e3233dda9382
DOC="$RAW/$CONTEXT.document"
MARK="$HOLD/$CONTEXT.hold"
CTX_ID="$E/SIGMA_V4B3_CONTEXT_ID.memory"
CTX_TEXT="$E/SIGMA_V4B3_CONTEXT_TEXT.memory"
PROGRESS="$E/SIGMA_V4B3_PROGRESS_LEDGER.memory"
COMPLETE="$E/SIGMA_V4B3_COMPLETION_LEDGER.memory"
STATUS="$E/SIGMA_V4B3_STATUS.memory"
FIXED_VM_INVOCATIONS=64

mkdir -p "$BASE" "$E" "$LOG"
exec 9>"$LOCK"
if ! "$P/bin/flock" -n 9; then
    printf 'HOLD=V4B3R1_PREFLIGHT_ALREADY_RUNNING\n'
    exit 20
fi

hash1() { "$P/bin/sha256sum" "$1" | "$P/bin/awk" '{print $1}'; }
SIGMAC_SHA=$(hash1 "$SIGMAC")
VM_SHA=$(hash1 "$VM")
SOURCE_SHA=$(hash1 "$SRC_REPO")

printf 'SIGMA_PHASE=V4B3R1_REAL_49C16_RC9_REPLAY_PREFLIGHT\n'
printf 'SIGMAC_SHA256=%s\n' "$SIGMAC_SHA"
printf 'VM_SHA256=%s\n' "$VM_SHA"
printf 'SOURCE_SHA256=%s\n' "$SOURCE_SHA"
printf 'REAL_CONTEXT=%s\n' "$CONTEXT"
printf 'SHADOW_BRAIN=%s\n' "$BRAIN"
printf 'PRODUCTION_BRAIN_WRITE_TARGET=NO\n'
printf 'PRODUCTION_RAW_READ_ONLY_SOURCE=YES\n'
printf 'HOST_WINDOW_SELECTION=NO\n'
printf 'HOST_COMPLETION_DECISION=NO\n'
printf 'HOST_RETRY_DECISION=NO\n'
printf 'HOST_LEARNING=NO\n'
printf 'FIXED_VM_INVOCATIONS=%s\n' "$FIXED_VM_INVOCATIONS"
printf 'SHADOW_INPUT_INSTALL=PARTIAL_HASH_CHMOD0400_ATOMIC_RENAME\n'

V24_PID_BEFORE=$("$P/bin/pgrep" -f 'RUN_SIGMA_CONTINUOUS_NATIVE_SELF_DIRECTED_V2_4.sh' | "$P/bin/head" -n1 || true)
printf 'PRODUCTION_V24_PID_BEFORE=%s\n' "$V24_PID_BEFORE"
[ -n "$V24_PID_BEFORE" ] || { printf 'HOLD=PRODUCTION_V24_NOT_RUNNING\n'; exit 21; }
[ "$SIGMAC_SHA" = "$EXPECTED_SIGMAC" ] || { printf 'HOLD=SIGMAC_IDENTITY_MISMATCH\n'; exit 22; }
[ "$VM_SHA" = "$EXPECTED_VM" ] || { printf 'HOLD=VM_IDENTITY_MISMATCH\n'; exit 23; }
[ "$SOURCE_SHA" = "$EXPECTED_SOURCE" ] || { printf 'HOLD=V4B3_SOURCE_IDENTITY_MISMATCH\n'; exit 24; }
[ -f "$DOC" ] || { printf 'HOLD=REAL_RAW_DOCUMENT_MISSING\n'; exit 25; }
[ -f "$MARK" ] || { printf 'HOLD=REAL_V24_HOLD_MARKER_MISSING\n'; exit 26; }

DOC_SHA_BEFORE=$(hash1 "$DOC")
MARK_SHA_BEFORE=$(hash1 "$MARK")
printf 'REAL_DOCUMENT_SHA256=%s\n' "$DOC_SHA_BEFORE"
printf 'REAL_HOLD_MARKER_SHA256_BEFORE=%s\n' "$MARK_SHA_BEFORE"
[ "$DOC_SHA_BEFORE" = "$CONTEXT" ] || { printf 'HOLD=REAL_DOCUMENT_SHA_MISMATCH\n'; exit 27; }
grep -F -x "CONTEXT_SHA256=$CONTEXT" "$MARK" >/dev/null || { printf 'HOLD=HOLD_CONTEXT_ID_MISMATCH\n'; exit 28; }
grep -F -x 'VM_RC=9' "$MARK" >/dev/null || { printf 'HOLD=HOLD_NOT_RC9\n'; exit 29; }
grep -F -x "VM_SHA256=$EXPECTED_VM" "$MARK" >/dev/null || { printf 'HOLD=HOLD_VM_IDENTITY_MISMATCH\n'; exit 30; }
printf 'V24_RC9_EVIDENCE=PASS\n'

cp -- "$SRC_REPO" "$SRC" || { printf 'HOLD=SOURCE_INSTALL_FAILED\n'; exit 31; }
INSTALLED_SOURCE_SHA=$(hash1 "$SRC")
printf 'INSTALLED_SOURCE_SHA256=%s\n' "$INSTALLED_SOURCE_SHA"
[ "$INSTALLED_SOURCE_SHA" = "$EXPECTED_SOURCE" ] || { printf 'HOLD=INSTALLED_SOURCE_IDENTITY_MISMATCH\n'; exit 32; }
rm -f -- "$BC.partial"
"$SIGMAC" "$SRC" "$BC.partial"
RC=$?
printf 'V4B3R1_SIGMAC_RC=%s\n' "$RC"
[ "$RC" -eq 0 ] || { printf 'HOLD=V4B3R1_COMPILE_FAILED\n'; exit 33; }
[ -s "$BC.partial" ] || { printf 'HOLD=V4B3R1_BYTECODE_EMPTY\n'; exit 34; }
mv -f -- "$BC.partial" "$BC"
chmod 0400 "$BC"
printf 'V4B3R1_BYTECODE_SHA256=%s\n' "$(hash1 "$BC")"

: > "$PROGRESS"
: > "$COMPLETE"
: > "$STATUS"
printf '%s' "$CONTEXT" > "$CTX_ID"
CTX_PART="$CTX_TEXT.partial.$$"
rm -f -- "$CTX_PART"
cp -- "$DOC" "$CTX_PART" || { printf 'HOLD=SHADOW_CONTEXT_COPY_FAILED\n'; exit 35; }
CTX_PART_SHA=$(hash1 "$CTX_PART")
printf 'SHADOW_CONTEXT_PARTIAL_SHA256=%s\n' "$CTX_PART_SHA"
[ "$CTX_PART_SHA" = "$CONTEXT" ] || { rm -f -- "$CTX_PART"; printf 'HOLD=SHADOW_CONTEXT_PARTIAL_SHA_MISMATCH\n'; exit 36; }
chmod 0400 "$CTX_PART" || { rm -f -- "$CTX_PART"; printf 'HOLD=SHADOW_CONTEXT_PARTIAL_CHMOD_FAILED\n'; exit 37; }
mv -f -- "$CTX_PART" "$CTX_TEXT" || { rm -f -- "$CTX_PART"; printf 'HOLD=SHADOW_CONTEXT_ATOMIC_RENAME_FAILED\n'; exit 38; }
SHADOW_CONTEXT_SHA=$(hash1 "$CTX_TEXT")
printf 'SHADOW_CONTEXT_SHA256=%s\n' "$SHADOW_CONTEXT_SHA"
printf 'SHADOW_CONTEXT_MODE=%s\n' "$("$P/bin/stat" -c '%a' "$CTX_TEXT")"
[ "$SHADOW_CONTEXT_SHA" = "$CONTEXT" ] || { printf 'HOLD=SHADOW_CONTEXT_COPY_MISMATCH\n'; exit 39; }

I=0
while [ "$I" -lt "$FIXED_VM_INVOCATIONS" ]; do
    RUNLOG="$LOG/$CONTEXT.$I.log"
    (
        cd "$BRAIN" || exit 40
        "$VM" "$BC"
    ) >"$RUNLOG" 2>&1
    VMRC=$?
    printf 'REAL_REPLAY_VM context=%s invocation=%s rc=%s\n' "$CONTEXT" "$I" "$VMRC"
    [ "$VMRC" -eq 0 ] || {
        printf 'HOLD=REAL_REPLAY_VM_FAILURE context=%s invocation=%s rc=%s log=%s\n' "$CONTEXT" "$I" "$VMRC" "$RUNLOG"
        exit 41
    }
    I=$((I + 1))
done

FINAL_STATUS=$(cat "$STATUS")
PROGRESS_COMMIT_COUNT=$(grep -c 'COMMIT=YES' "$PROGRESS" || true)
COMPLETION_COMMIT_COUNT=$(grep -c 'COMPLETE=YES' "$COMPLETE" || true)
printf 'FINAL_NATIVE_STATUS=%s\n' "$FINAL_STATUS"
printf 'PROGRESS_COMMIT_COUNT=%s\n' "$PROGRESS_COMMIT_COUNT"
printf 'COMPLETION_COMMIT_COUNT=%s\n' "$COMPLETION_COMMIT_COUNT"
printf 'LAST_PROGRESS_RECORD=%s\n' "$(tail -n 1 "$PROGRESS")"

if grep -F 'STATUS REFUSE_' "$LOG"/*.log >/dev/null 2>&1; then
    printf 'HOLD=REAL_CONTEXT_NATIVE_REFUSAL\n'
    grep -H -F 'STATUS REFUSE_' "$LOG"/*.log || true
    exit 42
fi
grep -F -x "CTX=$CONTEXT || COMPLETE=YES" "$COMPLETE" >/dev/null || { printf 'HOLD=REAL_CONTEXT_NOT_COMPLETED status=%s\n' "$FINAL_STATUS"; exit 43; }
[ "$COMPLETION_COMMIT_COUNT" -eq 1 ] || { printf 'HOLD=COMPLETION_NOT_IDEMPOTENT count=%s\n' "$COMPLETION_COMMIT_COUNT"; exit 44; }
[ "$PROGRESS_COMMIT_COUNT" -gt 0 ] || { printf 'HOLD=NO_NATIVE_PROGRESS_COMMITTED\n'; exit 45; }
[ "$FINAL_STATUS" = 'ALREADY_COMPLETE' ] || { printf 'HOLD=FIXED_EXTRA_INVOCATIONS_NOT_IDEMPOTENT status=%s\n' "$FINAL_STATUS"; exit 46; }

DOC_SHA_AFTER=$(hash1 "$DOC")
MARK_SHA_AFTER=$(hash1 "$MARK")
printf 'REAL_DOCUMENT_SHA256_AFTER=%s\n' "$DOC_SHA_AFTER"
printf 'REAL_HOLD_MARKER_SHA256_AFTER=%s\n' "$MARK_SHA_AFTER"
[ "$DOC_SHA_AFTER" = "$DOC_SHA_BEFORE" ] || { printf 'HOLD=PRODUCTION_RAW_DOCUMENT_CHANGED\n'; exit 47; }
[ "$MARK_SHA_AFTER" = "$MARK_SHA_BEFORE" ] || { printf 'HOLD=PRODUCTION_HOLD_MARKER_CHANGED\n'; exit 48; }
V24_PID_AFTER=$("$P/bin/pgrep" -f 'RUN_SIGMA_CONTINUOUS_NATIVE_SELF_DIRECTED_V2_4.sh' | "$P/bin/head" -n1 || true)
printf 'PRODUCTION_V24_PID_AFTER=%s\n' "$V24_PID_AFTER"
[ "$V24_PID_AFTER" = "$V24_PID_BEFORE" ] || { printf 'HOLD=PRODUCTION_V24_PID_CHANGED\n'; exit 49; }

printf '\nV4B3R1_REAL_49C16_RC9_REPLAY_PREFLIGHT=PASS\n'
printf 'REAL_49C16_RC9_CONTEXT_COMPLETED_BY_NATIVE_V4B3=PASS\n'
printf 'EXACT_PRODUCTION_DOCUMENT_BYTES_PRESERVED=PASS\n'
printf 'FIXED_64_VM_INVOCATIONS_NO_HOST_STOP_DECISION=PASS\n'
printf 'EXTRA_INVOCATIONS_AFTER_COMPLETION_IDEMPOTENT=PASS\n'
printf 'SHADOW_STATE_NAMESPACE_ISOLATION=PASS\n'
printf 'PRODUCTION_BRAIN_WRITE_TARGET=NO\n'
printf 'PRODUCTION_RAW_READ_ONLY_SOURCE=YES\n'
printf 'PRODUCTION_V24_REMAINED_RUNNING_SAME_PID=PASS\n'
printf 'HOST_WINDOW_SELECTION=NO\n'
printf 'HOST_COMPLETION_DECISION=NO\n'
printf 'HOST_RETRY_DECISION=NO\n'
printf 'HOST_LEARNING=NO\n'
printf 'REAL_V24_RC9_CONTEXT_RECOVERY=PROVEN_FOR_49C16_OBSERVED_CONTEXT_ONLY\n'
printf 'REMAINING_FOUR_OBSERVED_RC9_CONTEXTS=NOT_YET_PROVEN\n'
printf 'V4_PRODUCTION_PROMOTION_ALLOWED=NO\n'
printf 'BOUNDED_FILE_IO=NOT_PROVEN\n'
printf 'SEMANTIC_UNDERSTANDING=NOT_PROVEN\n'
printf 'NEXT_ACTION=CHECKPOINT_49C16_REAL_RECOVERY_THEN_REPLAY_REMAINING_FOUR_OBSERVED_RC9_CONTEXTS_WITH_NATIVE_V4B3\n'
