#!/data/data/com.termux/files/usr/bin/bash
set -u
set -o pipefail
umask 077

P=/data/data/com.termux/files/usr
HOME_SIGMA=/data/data/com.termux/files/home/SIGMA
REPO="$HOME_SIGMA/sigma-freedom-write"
BRAIN="$REPO/BRAIN/EXTRA BRAIN_OPPO_24826"
E="$BRAIN/.sigma_exec"

SIGMAC="$HOME_SIGMA/sigma_genesis1/native/sigmac"
VM="$HOME_SIGMA/sigma_genesis1/native/sigma-vm.v09_candidate"

EXPECTED_SIGMAC=65f69217ad44f33c1aa1d4c31678d38940cd3d0b96f41892e8280dac57ad6a71
EXPECTED_VM=029ae4b6acbee5558f7663a732f8d39a970166e8488d2c4fe62414eb39391c99

SELECT_SRC="$E/SIGMA_REAL_SURVEY_CURRICULUM_BRIDGE_V2_8R1.sigma"
SELECT_BC="$E/SIGMA_REAL_SURVEY_CURRICULUM_BRIDGE_V2_8R1.sigmab"
EXPECTED_SELECT_SOURCE=8d4fee26c5d0768aaec99eaa960d0cd7f52251680d86391f3dd4c3de89d430e8
EXPECTED_SELECT_BYTECODE=0244d7a6ea0888c95f7db97ee2df0e7f50bfcb7bae2a00fd9b48e2aa0dec1eb5

DEEP_SRC="$E/SIGMA_SELECTED_WORK_DEEP_RELEARN_V2_8D1.sigma"
DEEP_BC="$E/SIGMA_SELECTED_WORK_DEEP_RELEARN_V2_8D1.sigmab"
EXPECTED_DEEP_SOURCE=3da9195db5cf24fb3bc5094823ca13e52caa4335b6605c185e7921033079e8ce
EXPECTED_DEEP_BYTECODE=e23fd92ed4a554195505cc490d5114531320e32ffbb481a421ded36e9c94e2ff

V213_SRC="$E/SIGMA_GENERATION_AWARE_REVALIDATION_LIFECYCLE_V2_13R1.sigma"
V213_BC="$E/SIGMA_GENERATION_AWARE_REVALIDATION_LIFECYCLE_V2_13R1.sigmab"
EXPECTED_V213_SOURCE=8984a0beaefddb6656158eaed47080bc09955f79e9dcb0b59edcd2e0b670f107

CTRL_SRC="$E/SIGMA_GENERATION_AWARE_CLOSED_LOOP_CONTROLLER_V2_14C1.sigma"
CTRL_BC="$E/SIGMA_GENERATION_AWARE_CLOSED_LOOP_CONTROLLER_V2_14C1.sigmab"
EXPECTED_CTRL_SOURCE=1db8cd24432b85a5b4d6125e1f26e657df6bf47c429d763eb255c12ce201d972

REAL_SURVEY="$E/SIGMA_V25B2_DOCUMENT_SURVEY.memory"
SNAPSHOT="$HOME_SIGMA/SIGMA_V25_FULL_CORPUS_SURVEY/corpus_snapshot"

SELECT_SURVEY_PATH="$E/SIGMA_V28R1_SURVEY_PATH.memory"
SELECT_STATE="$E/SIGMA_V28R1_CURRICULUM_STATE.memory"
SELECTED_WORK="$E/SIGMA_V28R1_SELECTED_WORK.memory"

V213_SELECTED_EVENT="$E/SIGMA_V213R1_SELECTED_EVENT.memory"
V213_SURVEY_PATH="$E/SIGMA_V213R1_SURVEY_PATH.memory"
V213_EVIDENCE_PATH="$E/SIGMA_V213R1_REVISIT_EVIDENCE_PATH.memory"
V213_REVAL_STATE="$E/SIGMA_V213R1_REVALIDATION_STATE.memory"
V213_LIFE_STATE="$E/SIGMA_V213R1_LIFECYCLE_STATE.memory"

CTRL_SELECTED="$E/SIGMA_V214C1_SELECTED_WORK.memory"
CTRL_LIFECYCLE_PATH="$E/SIGMA_V214C1_LIFECYCLE_PATH.memory"
CTRL_REVISIT_DIR="$E/SIGMA_V214C1_REVISIT_STATE_DIR.memory"
CTRL_STATE="$E/SIGMA_V214C1_CONTROLLER_STATE.memory"
CTRL_EVENT="$E/SIGMA_V214C1_SELECTED_EVENT.memory"

D1_SNAPSHOT_DIR="$E/SIGMA_V28D1_SNAPSHOT_DIR.memory"
D1_ACTIVE_WORK="$E/SIGMA_V28D1_ACTIVE_WORK.memory"
D1_CURSOR="$E/SIGMA_V28D1_CURSOR.memory"
D1_EVIDENCE="$E/SIGMA_V28D1_DEEP_EVIDENCE.memory"

STATE="$HOME_SIGMA/SIGMA_V215R1_EVENT_DRIVEN_NEXT_WORK_TRANSITION_PREFLIGHT"
LOG="$STATE/log"
ARCHIVE_EVIDENCE="$STATE/archive_trigger_evidence.memory"
ARCHIVE_REVISIT_DIR="$STATE/archive_revisit_state"
NEGATIVE_REVISIT_DIR="$STATE/negative_revisit_state"
LOCK="$STATE/preflight.lock"

EXPECTED_FIRST=0ac783c25e93ee81fe130c55026323e74191fc82a7782974ed64614aed66485b
EXPECTED_SECOND=26d19552540508d564f76543e43858724c6e479d0544b50f23bf47b276c9d0f6

mkdir -p "$STATE" "$LOG" "$ARCHIVE_REVISIT_DIR" "$NEGATIVE_REVISIT_DIR"

exec 9>"$LOCK"
"$P/bin/flock" -n 9 || {
  printf 'HOLD=V215R1_PREFLIGHT_ALREADY_RUNNING\n'
  exit 20
}

hash1() { "$P/bin/sha256sum" "$1" | "$P/bin/awk" '{print $1}'; }
check_source() { [ "$(hash1 "$1")" = "$2" ]; }

printf 'SIGMA_PHASE=V215R1_EVENT_DRIVEN_REAL_NEXT_WORK_TRANSITION_PREFLIGHT\n'
printf 'HOST_WORK_SELECTION=NO\n'
printf 'HOST_STAGE_DECISION=NO\n'
printf 'HOST_ARCHIVE_DECISION=NO\n'
printf 'HOST_DOCUMENT_SELECTION=NO\n'
printf 'HOST_LEARNING=NO\n'
printf 'MECHANICAL_HOST_EVENT_DISPATCH=YES\n'
printf 'REAL_SURVEY_NEXT_WORK_SELECTION=YES\n'
printf 'SECOND_REAL_DOCUMENT_LEARNING_START=YES\n'
printf 'MULTI_DOCUMENT_AUTONOMOUS_CYCLE=NOT_PROVEN\n'

[ "$(hash1 "$SIGMAC")" = "$EXPECTED_SIGMAC" ] || exit 21
[ "$(hash1 "$VM")" = "$EXPECTED_VM" ] || exit 22
check_source "$SELECT_SRC" "$EXPECTED_SELECT_SOURCE" || exit 23
check_source "$DEEP_SRC" "$EXPECTED_DEEP_SOURCE" || exit 24
check_source "$V213_SRC" "$EXPECTED_V213_SOURCE" || exit 25
check_source "$CTRL_SRC" "$EXPECTED_CTRL_SOURCE" || exit 26
[ -f "$REAL_SURVEY" ] || exit 27
[ -d "$SNAPSHOT" ] || exit 28

REAL_SURVEY_SHA_BEFORE=$(hash1 "$REAL_SURVEY")

compile_exact() {
  SRC="$1"; BC="$2"; EXPECTED="$3"; LABEL="$4"
  "$P/bin/rm" -f -- "$BC.partial"
  "$SIGMAC" "$SRC" "$BC.partial"
  RC=$?
  printf '%s_SIGMAC_RC=%s\n' "$LABEL" "$RC"
  [ "$RC" -eq 0 ] || return 1
  SHA=$(hash1 "$BC.partial")
  printf '%s_BYTECODE_SHA256=%s\n' "$LABEL" "$SHA"
  [ "$SHA" = "$EXPECTED" ] || return 2
  "$P/bin/mv" -f -- "$BC.partial" "$BC"
  "$P/bin/chmod" 0400 "$BC"
}

compile_unpinned() {
  SRC="$1"; BC="$2"; LABEL="$3"
  "$P/bin/rm" -f -- "$BC.partial"
  "$SIGMAC" "$SRC" "$BC.partial"
  RC=$?
  printf '%s_SIGMAC_RC=%s\n' "$LABEL" "$RC"
  [ "$RC" -eq 0 ] || return 1
  "$P/bin/mv" -f -- "$BC.partial" "$BC"
  "$P/bin/chmod" 0400 "$BC"
  printf '%s_BYTECODE_SHA256=%s\n' "$LABEL" "$(hash1 "$BC")"
}

compile_exact "$SELECT_SRC" "$SELECT_BC" "$EXPECTED_SELECT_BYTECODE" SELECTOR || exit 30
compile_exact "$DEEP_SRC" "$DEEP_BC" "$EXPECTED_DEEP_BYTECODE" DEEP || exit 31
compile_unpinned "$V213_SRC" "$V213_BC" V213 || exit 32
compile_unpinned "$CTRL_SRC" "$CTRL_BC" V214C1 || exit 33

run_vm() {
  CASE_NAME="$1"; BC="$2"
  RUNLOG="$LOG/$CASE_NAME.log"
  (
    cd "$BRAIN" || exit 40
    "$VM" "$BC"
  ) >"$RUNLOG" 2>&1
  RC=$?
  printf '\n=== %s ===\n' "$CASE_NAME"
  printf 'VM_RC=%s\n' "$RC"
  "$P/bin/cat" "$RUNLOG"
  return "$RC"
}

"$P/bin/printf" '%s' "$REAL_SURVEY" > "$SELECT_SURVEY_PATH"
: > "$SELECT_STATE"
: > "$SELECTED_WORK"
run_vm REAL_SELECTOR_FIRST_WORK "$SELECT_BC" || exit 50
FIRST=$("$P/bin/cat" "$SELECTED_WORK")
printf 'FIRST_NATIVE_WORK=%s\n' "$FIRST"
[ "$FIRST" = "$EXPECTED_FIRST" ] || exit 51
FIRST_SELECTOR_STATE_SHA=$(hash1 "$SELECT_STATE")
printf 'FIRST_SELECTOR_STATE_SHA256=%s\n' "$FIRST_SELECTOR_STATE_SHA"

"$P/bin/cat" > "$ARCHIVE_EVIDENCE" <<EOF_ARCHIVE_EVID
WORK=$FIRST || GEN=| || CURSOR= || BEST_LOCAL_RELATION=of => the || COMMIT=YES
EOF_ARCHIVE_EVID

"$P/bin/printf" '%s' "$FIRST::|::REVALIDATE_REVISIT_GENERATION" > "$V213_SELECTED_EVENT"
"$P/bin/printf" '%s' "$REAL_SURVEY" > "$V213_SURVEY_PATH"
"$P/bin/printf" '%s' "$ARCHIVE_EVIDENCE" > "$V213_EVIDENCE_PATH"
: > "$V213_REVAL_STATE"
: > "$V213_LIFE_STATE"
run_vm NATIVE_ARCHIVE_TRIGGER "$V213_BC" || exit 52
"$P/bin/grep" -F 'REVALIDATION_RESULT REOBSERVED' "$LOG/NATIVE_ARCHIVE_TRIGGER.log" >/dev/null || exit 53
"$P/bin/grep" -F 'LIFECYCLE_ACTION ARCHIVE_FOR_NOW' "$LOG/NATIVE_ARCHIVE_TRIGGER.log" >/dev/null || exit 54

"$P/bin/printf" '|' > "$ARCHIVE_REVISIT_DIR/$FIRST.generation"
: > "$ARCHIVE_REVISIT_DIR/$FIRST.cursor"
: > "$ARCHIVE_REVISIT_DIR/$FIRST.evidence"
"$P/bin/printf" '%s' "$FIRST" > "$CTRL_SELECTED"
"$P/bin/printf" '%s' "$V213_LIFE_STATE" > "$CTRL_LIFECYCLE_PATH"
"$P/bin/printf" '%s' "$ARCHIVE_REVISIT_DIR" > "$CTRL_REVISIT_DIR"
: > "$CTRL_STATE"
: > "$CTRL_EVENT"
run_vm NATIVE_SELECT_NEXT_WORK_EVENT "$CTRL_BC" || exit 55
"$P/bin/grep" -F 'NEXT_STAGE SELECT_NEXT_WORK' "$LOG/NATIVE_SELECT_NEXT_WORK_EVENT.log" >/dev/null || exit 56
"$P/bin/grep" -F 'EVENT_READY 1' "$LOG/NATIVE_SELECT_NEXT_WORK_EVENT.log" >/dev/null || exit 57
NEXT_EVENT=$("$P/bin/cat" "$CTRL_EVENT")
printf 'NATIVE_NEXT_WORK_EVENT=%s\n' "$NEXT_EVENT"
[ "$NEXT_EVENT" = "$FIRST::|::SELECT_NEXT_WORK" ] || exit 58

STAGE="${NEXT_EVENT##*::}"
printf 'MECHANICAL_DISPATCH_STAGE=%s\n' "$STAGE"
[ "$STAGE" = 'SELECT_NEXT_WORK' ] || exit 59
run_vm REAL_SELECTOR_SECOND_WORK "$SELECT_BC" || exit 60
SECOND=$("$P/bin/cat" "$SELECTED_WORK")
printf 'SECOND_NATIVE_WORK=%s\n' "$SECOND"
[ "$SECOND" = "$EXPECTED_SECOND" ] || exit 61
[ "$SECOND" != "$FIRST" ] || exit 62
SECOND_SELECTOR_STATE_SHA=$(hash1 "$SELECT_STATE")
printf 'SECOND_SELECTOR_STATE_SHA256=%s\n' "$SECOND_SELECTOR_STATE_SHA"
[ "$SECOND_SELECTOR_STATE_SHA" != "$FIRST_SELECTOR_STATE_SHA" ] || exit 63

SECOND_DOC="$SNAPSHOT/$SECOND.document"
[ -f "$SECOND_DOC" ] || exit 64
SECOND_DOC_SHA_BEFORE=$(hash1 "$SECOND_DOC")
printf 'SECOND_DOCUMENT_SHA256_BEFORE=%s\n' "$SECOND_DOC_SHA_BEFORE"

if [ -f "$D1_ACTIVE_WORK" ]; then "$P/bin/cp" -- "$D1_ACTIVE_WORK" "$STATE/d1_active_before.reference"; fi
if [ -f "$D1_CURSOR" ]; then "$P/bin/cp" -- "$D1_CURSOR" "$STATE/d1_cursor_before.reference"; fi
if [ -f "$D1_EVIDENCE" ]; then "$P/bin/cp" -- "$D1_EVIDENCE" "$STATE/d1_evidence_before.reference"; fi

"$P/bin/printf" '%s' "$SNAPSHOT" > "$D1_SNAPSHOT_DIR"
: > "$D1_ACTIVE_WORK"
: > "$D1_CURSOR"
: > "$D1_EVIDENCE"
run_vm SECOND_REAL_WORK_SEGMENT0 "$DEEP_BC" || exit 65
"$P/bin/grep" -F "SELECTED_WORK $SECOND" "$LOG/SECOND_REAL_WORK_SEGMENT0.log" >/dev/null || exit 66
"$P/bin/grep" -F 'DOCUMENT_EXISTS 1' "$LOG/SECOND_REAL_WORK_SEGMENT0.log" >/dev/null || exit 67
"$P/bin/grep" -F 'WORK_SWITCHED 1' "$LOG/SECOND_REAL_WORK_SEGMENT0.log" >/dev/null || exit 68
"$P/bin/grep" -F 'SEGMENT_INDEX 0' "$LOG/SECOND_REAL_WORK_SEGMENT0.log" >/dev/null || exit 69
"$P/bin/grep" -F 'EVIDENCE_READY 1' "$LOG/SECOND_REAL_WORK_SEGMENT0.log" >/dev/null || exit 70
"$P/bin/grep" -F 'CURSOR_APPEND_RC 0' "$LOG/SECOND_REAL_WORK_SEGMENT0.log" >/dev/null || exit 71
SECOND_EVID_SHA_AFTER_SEG0=$(hash1 "$D1_EVIDENCE")
SECOND_CURSOR_SHA_AFTER_SEG0=$(hash1 "$D1_CURSOR")
printf 'SECOND_WORK_EVIDENCE_SHA256_AFTER_SEG0=%s\n' "$SECOND_EVID_SHA_AFTER_SEG0"
printf 'SECOND_WORK_CURSOR_SHA256_AFTER_SEG0=%s\n' "$SECOND_CURSOR_SHA_AFTER_SEG0"

run_vm SECOND_REAL_WORK_FRESH_VM_CONTINUATION "$DEEP_BC" || exit 72
"$P/bin/grep" -F "SELECTED_WORK $SECOND" "$LOG/SECOND_REAL_WORK_FRESH_VM_CONTINUATION.log" >/dev/null || exit 73
"$P/bin/grep" -F 'WORK_SWITCHED 0' "$LOG/SECOND_REAL_WORK_FRESH_VM_CONTINUATION.log" >/dev/null || exit 74
"$P/bin/grep" -F 'SEGMENT_INDEX 1' "$LOG/SECOND_REAL_WORK_FRESH_VM_CONTINUATION.log" >/dev/null || exit 75

NEG_LIFE="$STATE/negative_revisit_lifecycle.memory"
"$P/bin/cat" > "$NEG_LIFE" <<EOF_NEG_LIFE
WORK=$FIRST || CYCLE=| || ACTION=REVISIT || FROM_RESULT=NOT_REOBSERVED || COMMIT=YES
EOF_NEG_LIFE
"$P/bin/printf" '|' > "$NEGATIVE_REVISIT_DIR/$FIRST.generation"
: > "$NEGATIVE_REVISIT_DIR/$FIRST.cursor"
: > "$NEGATIVE_REVISIT_DIR/$FIRST.evidence"
"$P/bin/printf" '%s' "$FIRST" > "$CTRL_SELECTED"
"$P/bin/printf" '%s' "$NEG_LIFE" > "$CTRL_LIFECYCLE_PATH"
"$P/bin/printf" '%s' "$NEGATIVE_REVISIT_DIR" > "$CTRL_REVISIT_DIR"
: > "$CTRL_STATE"
: > "$CTRL_EVENT"
run_vm NEGATIVE_NON_SELECTION_EVENT "$CTRL_BC" || exit 76
NEG_EVENT=$("$P/bin/cat" "$CTRL_EVENT")
NEG_STAGE="${NEG_EVENT##*::}"
printf 'NEGATIVE_NATIVE_EVENT=%s\n' "$NEG_EVENT"
printf 'NEGATIVE_NATIVE_STAGE=%s\n' "$NEG_STAGE"
[ "$NEG_STAGE" = 'EXECUTE_REVISIT' ] || exit 77
SELECT_STATE_SHA_BEFORE_NEG=$(hash1 "$SELECT_STATE")
if [ "$NEG_STAGE" = 'SELECT_NEXT_WORK' ]; then
  run_vm NEGATIVE_SHOULD_NOT_SELECT "$SELECT_BC" || exit 78
fi
SELECT_STATE_SHA_AFTER_NEG=$(hash1 "$SELECT_STATE")
[ "$SELECT_STATE_SHA_AFTER_NEG" = "$SELECT_STATE_SHA_BEFORE_NEG" ] || exit 79

: > "$SELECT_STATE"
: > "$SELECTED_WORK"
run_vm REPLAY_SELECTOR_FIRST "$SELECT_BC" || exit 80
REPLAY_FIRST=$("$P/bin/cat" "$SELECTED_WORK")
[ "$REPLAY_FIRST" = "$FIRST" ] || exit 81
run_vm REPLAY_SELECTOR_SECOND "$SELECT_BC" || exit 82
REPLAY_SECOND=$("$P/bin/cat" "$SELECTED_WORK")
[ "$REPLAY_SECOND" = "$SECOND" ] || exit 83
REPLAY_SELECTOR_STATE_SHA=$(hash1 "$SELECT_STATE")
[ "$REPLAY_SELECTOR_STATE_SHA" = "$SECOND_SELECTOR_STATE_SHA" ] || exit 84

REAL_SURVEY_SHA_AFTER=$(hash1 "$REAL_SURVEY")
SECOND_DOC_SHA_AFTER=$(hash1 "$SECOND_DOC")
printf 'REAL_SURVEY_SHA256_AFTER=%s\n' "$REAL_SURVEY_SHA_AFTER"
printf 'SECOND_DOCUMENT_SHA256_AFTER=%s\n' "$SECOND_DOC_SHA_AFTER"
[ "$REAL_SURVEY_SHA_AFTER" = "$REAL_SURVEY_SHA_BEFORE" ] || exit 85
[ "$SECOND_DOC_SHA_AFTER" = "$SECOND_DOC_SHA_BEFORE" ] || exit 86

printf '\nV215R1_EVENT_DRIVEN_REAL_NEXT_WORK_TRANSITION_PREFLIGHT=PASS\n'
printf 'NATIVE_ARCHIVE_TO_SELECT_NEXT_WORK_EVENT=PASS\n'
printf 'REAL_NATIVE_FIRST_TO_SECOND_WORK_TRANSITION=PROVEN_IN_FROZEN_56_DOCUMENT_SURVEY_SCOPE\n'
printf 'SECOND_REAL_WORK_DIFFERS_FROM_FIRST=PASS\n'
printf 'SECOND_REAL_WORK_NATIVE_DOCUMENT_RESOLUTION=PASS\n'
printf 'SECOND_REAL_WORK_NATIVE_LEARNING_STARTED=PASS\n'
printf 'SECOND_REAL_WORK_PERSISTED_CURSOR_INFLUENCES_FRESH_VM=PASS\n'
printf 'NON_SELECTION_EVENT_DOES_NOT_TRIGGER_SELECTOR=PASS\n'
printf 'DETERMINISTIC_REAL_SELECTOR_REPLAY=PASS\n'
printf 'REAL_SURVEY_MUTATED=NO\n'
printf 'SECOND_SELECTED_DOCUMENT_MUTATED=NO\n'
printf 'HOST_WORK_SELECTION=NO\n'
printf 'HOST_STAGE_DECISION=NO\n'
printf 'HOST_ARCHIVE_DECISION=NO\n'
printf 'HOST_DOCUMENT_SELECTION=NO\n'
printf 'HOST_LEARNING=NO\n'
printf 'MECHANICAL_HOST_EVENT_DISPATCH=YES\n'
printf 'MULTI_DOCUMENT_AUTONOMOUS_CYCLE=NOT_PROVEN\n'
printf 'SECOND_WORK_COMPLETE_CYCLE=NOT_PROVEN\n'
printf 'GENERAL_AUTONOMOUS_CYCLE_EXECUTION=NOT_PROVEN\n'
printf 'SEMANTIC_TRUTH_VALIDATION=NOT_PROVEN\n'
printf 'SEMANTIC_UNDERSTANDING=NOT_PROVEN\n'
printf 'BOUNDED_FILE_IO=NOT_PROVEN\n'
printf 'MID_APPEND_CRASH_ATOMICITY=NOT_PROVEN\n'
printf 'PRODUCTION_LEARNER_MEMORY_MUTATED=NO\n'
printf 'NEXT_ACTION=CHECKPOINT_V215R1_THEN_BUILD_SECOND_REAL_WORK_COMPLETE_CYCLE_PREFLIGHT\n'
