#!/usr/bin/env bash
set -euo pipefail
# Static/mechanical design audit for the six request-defined crash windows.
# No SIGMA VM, Internet, Oppo process or production state is touched.
HERE="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
for token in \
  'raw.response' \
  'transport.receipt.json' \
  'native.output' \
  'staging' \
  'SEALED' \
  'IDEMPOTENT_REUSE'
do
  grep -R -Fq "$token" "$HERE/host" || { echo "CRASH_MATRIX=FAIL_MISSING_MECHANIC:$token"; exit 2; }
done
cat <<'OUT'
CRASH_WINDOW_1_BEFORE_DOWNLOAD_COMMIT=DESIGNED_FETCH_ID_REPLAY_SAFE
CRASH_WINDOW_2_AFTER_RAW_BEFORE_NATIVE=DESIGNED_RAW_RECEIPT_REUSABLE_NO_SEMANTIC_REDECISION_BY_HOST
CRASH_WINDOW_3_DURING_NATIVE_EXECUTION=DESIGNED_NO_NATIVE_OUTPUT_COMMIT_UNTIL_EXACT_OUTPUT_EXISTS
CRASH_WINDOW_4_AFTER_NATIVE_BEFORE_QUEUE=DESIGNED_NATIVE_BYTES_HASH_ADDRESSABLE
CRASH_WINDOW_5_DURING_QUEUE_COMMIT=DESIGNED_STAGING_FSYNC_ATOMIC_RENAME_SEALED_MARKER
CRASH_WINDOW_6_AFTER_QUEUE_BEFORE_NEXT_CYCLE=DESIGNED_QUEUE_ITEM_IDEMPOTENT_REUSE
CRASH_MATRIX_RUNTIME_KILL_TEST=NOT_RUN_ON_OPPO
CRASH_WINDOW_MATRIX_STATIC=PASS
OUT
