#!/usr/bin/env bash
set -euo pipefail
# Harness only. The implementation request forbids running this on Oppo before review.
[ "${SURVIVAL_REVIEW_VERDICT:-}" = APPROVE_FOR_OPPO_PREFLIGHT_ONLY ] || { echo 'HOLD=SURVIVAL_MASTER_PREFLIGHT_APPROVAL_MISSING'; exit 2; }
echo 'PREFLIGHT_HARNESS=ARMED_BY_REVIEW'
echo 'LOCKED_SIGMAC_COMPILE=NOT_EXECUTED_BY_THIS_STATIC_HARNESS'
echo 'LOCKED_VM_RUNTIME=NOT_EXECUTED_BY_THIS_STATIC_HARNESS'
echo 'REQUIRED_FUTURE_SEQUENCE=IDENTITY_GATE_COMPILE_FREEZE_DYNAMIC_NEGATIVE_RECOVERY_REAL_PUBLIC_CYCLE_RESTART_NO_DUPLICATE'
exit 2
