#!/usr/bin/env bash
set -uo pipefail

EXPECTED_COMPILER_SHA256="65f69217ad44f33c1aa1d4c31678d38940cd3d0b96f41892e8280dac57ad6a71"
EXPECTED_VM_SHA256="029ae4b6acbee5558f7663a732f8d39a970166e8488d2c4fe62414eb39391c99"

if [ "$#" -ne 10 ]; then
    printf 'usage: %s TEST_ID FIELD QUESTION NEW_FIELD PRIOR_STATUS SOURCE_PATH EXACT_SCOPE NOT_PROVEN_BEYOND PRIOR_INSUFFICIENCY OUTPUT_BASE\n' "$0" >&2
    exit 64
fi

TEST_ID="$1"
FIELD="$2"
QUESTION="$3"
NEW_FIELD_CLOSED="$4"
PRIOR_STATUS="$5"
SRC="$6"
EXACT_SCOPE="$7"
NOT_PROVEN_BEYOND="$8"
PRIOR_EVIDENCE_INSUFFICIENT_BECAUSE="$9"
OUTPUT_BASE="${10}"

if [ ! -f "./native/sigmac" ] || [ ! -f "./native/sigma-vm.v09_candidate" ]; then
    printf 'required native binaries are absent in %s\n' "$PWD" >&2
    exit 66
fi

if [ ! -f "$SRC" ]; then
    printf 'source fixture not found: %s\n' "$SRC" >&2
    exit 66
fi

COMPILER_SHA256="$(sha256sum ./native/sigmac | awk '{print $1}')"
VM_SHA256="$(sha256sum ./native/sigma-vm.v09_candidate | awk '{print $1}')"

if [ "$COMPILER_SHA256" != "$EXPECTED_COMPILER_SHA256" ] || [ "$VM_SHA256" != "$EXPECTED_VM_SHA256" ]; then
    printf 'toolchain identity changed before test %s\n' "$TEST_ID" >&2
    exit 78
fi

RUN_ID="$(date +%Y%m%d_%H%M%S)_$$"
BC_RUN=".sigma_exec/test_${RUN_ID}.sigmab"
RUN_DIR="${OUTPUT_BASE}/${TEST_ID}/${RUN_ID}"

mkdir -p .sigma_exec "$RUN_DIR"

COMPILER_STDOUT="$RUN_DIR/compiler.stdout"
COMPILER_STDERR="$RUN_DIR/compiler.stderr"
VM_STDOUT="$RUN_DIR/vm.stdout"
VM_STDERR="$RUN_DIR/vm.stderr"
RAW_STDOUT="$RUN_DIR/raw.stdout"
RAW_STDERR="$RUN_DIR/raw.stderr"
RECORD="$RUN_DIR/record.txt"
BYTECODE_COPY="$RUN_DIR/bytecode.sigmab"

rm -f "$BC_RUN" "$COMPILER_STDOUT" "$COMPILER_STDERR" "$VM_STDOUT" "$VM_STDERR"

set +e
./native/sigmac "$SRC" "$BC_RUN" >"$COMPILER_STDOUT" 2>"$COMPILER_STDERR" \
&& \
./native/sigma-vm.v09_candidate "$BC_RUN" >"$VM_STDOUT" 2>"$VM_STDERR"
CHAIN_RC=$?
set -e

if [ -e "$VM_STDOUT" ] || [ -e "$VM_STDERR" ]; then
    COMPILE_RC=0
    VM_RC="$CHAIN_RC"
    VM_EXECUTED=YES
else
    COMPILE_RC="$CHAIN_RC"
    VM_RC=NOT_RUN
    VM_EXECUTED=NO
    : >"$VM_STDOUT"
    : >"$VM_STDERR"
fi

cat "$COMPILER_STDOUT" "$VM_STDOUT" >"$RAW_STDOUT"
cat "$COMPILER_STDERR" "$VM_STDERR" >"$RAW_STDERR"

SOURCE_SHA256="$(sha256sum "$SRC" | awk '{print $1}')"
RAW_STDOUT_SHA256="$(sha256sum "$RAW_STDOUT" | awk '{print $1}')"
RAW_STDERR_SHA256="$(sha256sum "$RAW_STDERR" | awk '{print $1}')"
COMPILER_STDOUT_SHA256="$(sha256sum "$COMPILER_STDOUT" | awk '{print $1}')"
COMPILER_STDERR_SHA256="$(sha256sum "$COMPILER_STDERR" | awk '{print $1}')"
VM_STDOUT_SHA256="$(sha256sum "$VM_STDOUT" | awk '{print $1}')"
VM_STDERR_SHA256="$(sha256sum "$VM_STDERR" | awk '{print $1}')"

if [ -f "$BC_RUN" ]; then
    BYTECODE_CREATED=YES
    BYTECODE_SHA256="$(sha256sum "$BC_RUN" | awk '{print $1}')"
    cp "$BC_RUN" "$BYTECODE_COPY"
    BYTECODE_EVIDENCE_COPY_PATH="$BYTECODE_COPY"
else
    BYTECODE_CREATED=NO
    BYTECODE_SHA256=NOT_CREATED
    BYTECODE_EVIDENCE_COPY_PATH=NOT_CREATED
fi

cat >"$RECORD" <<EOF
TEST_ID=$TEST_ID
FIELD=$FIELD
QUESTION=$QUESTION
PRIOR_STATUS=$PRIOR_STATUS
WHY_NEW_TEST_IS_REQUIRED=$PRIOR_EVIDENCE_INSUFFICIENT_BECAUSE
NEW_FIELD_CLOSED=$NEW_FIELD_CLOSED
PRIOR_EVIDENCE_INSUFFICIENT_BECAUSE=$PRIOR_EVIDENCE_INSUFFICIENT_BECAUSE
SOURCE_PATH=$SRC
SOURCE_SHA256=$SOURCE_SHA256
COMPILER_SHA256=$COMPILER_SHA256
VM_SHA256=$VM_SHA256
RUN_ID=$RUN_ID
BYTECODE_PATH=$BC_RUN
BYTECODE_SHA256=$BYTECODE_SHA256
BYTECODE_CREATED=$BYTECODE_CREATED
BYTECODE_EVIDENCE_COPY_PATH=$BYTECODE_EVIDENCE_COPY_PATH
COMPILE_RC=$COMPILE_RC
VM_EXECUTED=$VM_EXECUTED
VM_RC=$VM_RC
CHAIN_RC=$CHAIN_RC
COMPILER_RAW_STDOUT_PATH=$COMPILER_STDOUT
COMPILER_RAW_STDOUT_SHA256=$COMPILER_STDOUT_SHA256
COMPILER_RAW_STDERR_PATH=$COMPILER_STDERR
COMPILER_RAW_STDERR_SHA256=$COMPILER_STDERR_SHA256
VM_RAW_STDOUT_PATH=$VM_STDOUT
VM_RAW_STDOUT_SHA256=$VM_STDOUT_SHA256
VM_RAW_STDERR_PATH=$VM_STDERR
VM_RAW_STDERR_SHA256=$VM_STDERR_SHA256
RAW_STDOUT_PATH=$RAW_STDOUT
RAW_STDOUT_SHA256=$RAW_STDOUT_SHA256
RAW_STDERR_PATH=$RAW_STDERR
RAW_STDERR_SHA256=$RAW_STDERR_SHA256
OBSERVATION=RAW_CAPTURE_PRESERVED;EXTERNAL_SEMANTIC_EVALUATION_NOT_APPLIED
STATUS=NOT_PROVEN
EXACT_SCOPE=$EXACT_SCOPE
NOT_PROVEN_BEYOND=$NOT_PROVEN_BEYOND
DUPLICATE_CAPABILITY_TEST=NO
PRE_VM_ANSWER_ACCESS=NO
PRE_VM_HOST_DERIVATION=NO
ANSWER_IN_SOURCE=NO
ANSWER_IN_ARGV=NO
ANSWER_IN_ENV=NO
ANSWER_IN_STDIN=NO
HOST_SEMANTICS_SUBSTITUTION=NO
GPT_EXPECTED_MEANING_INJECTED=NO
CANONICAL_SIGMA_VM_FOOTER_USED=YES
PROVENANCE=BRAIN/EVIDENCE/SIGMA_PSI/WINDOW_J4_SEMANTIC_RUNTIME/13_RUNTIME_REOPEN_20260829/01_PHASE1_EXECUTION_MATRIX.tsv
EOF

printf '%s\t%s\t%s\t%s\t%s\n' "$TEST_ID" "$RUN_ID" "$COMPILE_RC" "$VM_RC" "$RECORD"
exit 0
