interface Env { STAGING:R2Bucket; HKA_PRODUCTION_BRIDGE_AUTH_TOKEN:string; }
type RunIndex={window_id:string;tree_slug:string;prompt_commit_sha:string;batch_id:string;run_id:string;run_prefix:string;status:"PRODUCTION_ACTIVE"|"QA_PENDING";create_only:true;created_at:string;completed_at?:string;manifest_sha256?:string;package_sha256?:string;expected_object_count?:number};
const ASSET_RE=/^HKA-VIS-W\d{2}-\d{4}$/;const SHA_RE=/^[a-f0-9]{64}$/;const RUN_RE=/^HKA-W\d{2}-B\d{2}-R\d{2}$/;
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8"}});
function must(ok:any,m:string):asserts ok{if(!ok)throw new Error(m)}
function auth(r:Request,e:Env){if(!e.HKA_PRODUCTION_BRIDGE_AUTH_TOKEN||r.headers.get("authorization")!==`Bearer ${e.HKA_PRODUCTION_BRIDGE_AUTH_TOKEN}`)throw new Response(JSON.stringify({error:"UNAUTHORIZED"}),{status:401,headers:{"content-type":"application/json"}})}
async function sha256(ab:ArrayBuffer){const h=await crypto.subtle.digest("SHA-256",ab);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function prefix(b:any){must(/^W\d{2}$/.test(b.window_id),"INVALID_WINDOW_ID");must(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(b.tree_slug),"INVALID_TREE_SLUG");must(/^[a-f0-9]{40}$/.test(b.prompt_commit_sha),"INVALID_PROMPT_SHA");must(/^HKA-W\d{2}-B\d{2}$/.test(b.batch_id),"INVALID_BATCH_ID");must(RUN_RE.test(b.run_id),"INVALID_RUN_ID");must(b.run_id.startsWith(`${b.batch_id}-R`),"BATCH_RUN_MISMATCH");return `tmp/v1/windows/${b.window_id}-${b.tree_slug}/prompt-commit/${b.prompt_commit_sha}/batches/${b.batch_id}/runs/${b.run_id}/`}
async function createOnly(bucket:R2Bucket,key:string,body:any,opts:R2PutOptions={}){const h=new Headers();h.set("If-None-Match","*");const o=await bucket.put(key,body,{...opts,onlyIf:h});if(!o)throw new Error(`OBJECT_ALREADY_EXISTS:${key}`);return o}
async function getRun(e:Env,id:string){const o=await e.STAGING.get(`_bridge/v1/run-index/${id}.json`);if(!o)throw new Error("RUN_NOT_FOUND");return await o.json<RunIndex>()}
async function setRun(e:Env,r:RunIndex){await e.STAGING.put(`_bridge/v1/run-index/${r.run_id}.json`,JSON.stringify(r),{httpMetadata:{contentType:"application/json"}})}
export default {async fetch(request:Request,env:Env){try{auth(request,env);const p=new URL(request.url).pathname;
if(request.method==="POST"&&p==="/v1/production/runs"){const b:any=await request.json();const rp=prefix(b);const key=`_bridge/v1/run-index/${b.run_id}.json`;if(await env.STAGING.head(key))return json({error:"RUN_ALREADY_EXISTS"},409);const r:RunIndex={window_id:b.window_id,tree_slug:b.tree_slug,prompt_commit_sha:b.prompt_commit_sha,batch_id:b.batch_id,run_id:b.run_id,run_prefix:rp,status:"PRODUCTION_ACTIVE",create_only:true,created_at:new Date().toISOString()};await createOnly(env.STAGING,key,JSON.stringify(r),{httpMetadata:{contentType:"application/json"}});return json({status:r.status,run_id:r.run_id,run_prefix:rp,create_only:true})}
let m=p.match(/^\/v1\/production\/runs\/([^/]+)\/assets$/);if(request.method==="POST"&&m){const r=await getRun(env,m[1]);must(r.status==="PRODUCTION_ACTIVE","RUN_NOT_ACTIVE");const fd=await request.formData();const f=fd.get("file");must(f instanceof File,"FILE_REQUIRED");const a=String(fd.get("asset_id")||""),v=String(fd.get("variant")||""),ex=String(fd.get("sha256")||"");must(ASSET_RE.test(a),"INVALID_ASSET_ID");must(v==="CLEAN_MASTER"||v==="BRANDED_FINAL","INVALID_VARIANT");must(SHA_RE.test(ex),"INVALID_SHA256");const ab=await f.arrayBuffer(),ac=await sha256(ab);must(ac===ex,"SHA256_MISMATCH");const ext=(f.name.split(".").pop()||"png").toLowerCase();const leaf=v==="CLEAN_MASTER"?`clean/${ac}/${a}_CLEAN_MASTER.${ext}`:`branded/${ac}/${a}_BRANDED_FINAL.${ext}`;const key=`${r.run_prefix}assets/${a}/${leaf}`;const o=await createOnly(env.STAGING,key,ab,{sha256:ac,httpMetadata:{contentType:f.type||"application/octet-stream"},customMetadata:{asset_id:a,variant:v,sha256:ac,run_id:r.run_id}});return json({status:"STORED_VERIFIED",bucket:"hka-c4k-staging",key,sha256_expected:ex,sha256_verified:ac,byte_length:ab.byteLength,etag:o.etag})}
m=p.match(/^\/v1\/production\/runs\/([^/]+)\/records$/);if(request.method==="POST"&&m){const r=await getRun(env,m[1]),fd=await request.formData(),f=fd.get("file");must(f instanceof File,"FILE_REQUIRED");const t=String(fd.get("record_type")||""),ex=String(fd.get("sha256")||""),a=String(fd.get("asset_id")||"");must(SHA_RE.test(ex),"INVALID_SHA256");const map:Record<string,string>={BATCH_MANIFEST_JSON:"manifests/BATCH_MANIFEST.json",BATCH_MANIFEST_SHA256:"manifests/BATCH_MANIFEST.sha256",BATCH_PROMPTS_MD:"prompts/BATCH_PROMPTS.md",PRODUCTION_REPORT_MD:"reports/PRODUCTION_REPORT.md",SELF_QA_REPORT_JSON:"reports/SELF_QA_REPORT.json",SHA256SUMS_TXT:"checksums/SHA256SUMS.txt",PRODUCTION_PACKAGE_ZIP:`packages/${r.batch_id}-${r.run_id}.zip`};let rel=map[t];if(t==="ASSET_METADATA"){must(ASSET_RE.test(a),"ASSET_ID_REQUIRED");rel=`assets/${a}/metadata/${a}_ASSET.json`}must(!!rel,"INVALID_RECORD_TYPE");const ab=await f.arrayBuffer(),ac=await sha256(ab);must(ac===ex,"SHA256_MISMATCH");const key=r.run_prefix+rel,o=await createOnly(env.STAGING,key,ab,{sha256:ac,httpMetadata:{contentType:f.type||"application/octet-stream"},customMetadata:{record_type:t,sha256:ac,run_id:r.run_id}});return json({status:"STORED_VERIFIED",bucket:"hka-c4k-staging",key,sha256_verified:ac,byte_length:ab.byteLength,etag:o.etag})}
m=p.match(/^\/v1\/production\/runs\/([^/]+)\/complete$/);if(request.method==="POST"&&m){const r=await getRun(env,m[1]),b:any=await request.json();must(SHA_RE.test(b.manifest_sha256),"INVALID_MANIFEST_SHA");must(SHA_RE.test(b.package_sha256),"INVALID_PACKAGE_SHA");const l=await env.STAGING.list({prefix:r.run_prefix,limit:1000});if(b.expected_object_count>0)must(l.objects.length===b.expected_object_count,"OBJECT_COUNT_MISMATCH");const marker={run_id:r.run_id,status:"QA_PENDING",manifest_sha256:b.manifest_sha256,package_sha256:b.package_sha256,verified_object_count:l.objects.length,completed_at:new Date().toISOString()};await createOnly(env.STAGING,`${r.run_prefix}_bridge/PRODUCTION_COMPLETE.json`,JSON.stringify(marker),{httpMetadata:{contentType:"application/json"}});Object.assign(r,{status:"QA_PENDING",completed_at:marker.completed_at,manifest_sha256:b.manifest_sha256,package_sha256:b.package_sha256,expected_object_count:l.objects.length});await setRun(env,r);return json(marker)}return json({error:"NOT_FOUND"},404)}catch(e:any){if(e instanceof Response)return e;return json({error:e?.message||String(e)},400)}}};
